/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package NavigationController;

/**
 *
 * @author Gisward
 */
public class NavigationView extends javax.swing.JFrame 
{
    NavigationController parentNavigationController;
    
    /** 
     * Creates new form NavigationView 
     * @param parentNavigationController the original NavigationController object
     */
    public NavigationView(NavigationController parentNavigationController) 
    {
        this.parentNavigationController = parentNavigationController;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        notificationButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        statisticButton = new javax.swing.JButton();
        foodRecButton = new javax.swing.JButton();
        intakeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navigationPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        notificationButton.setBackground(new java.awt.Color(0, 204, 153));
        notificationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/notifications_icon.png"))); // NOI18N
        notificationButton.setToolTipText("Notifications");
        notificationButton.setMaximumSize(new java.awt.Dimension(66, 66));
        notificationButton.setMinimumSize(new java.awt.Dimension(66, 66));
        notificationButton.setPreferredSize(new java.awt.Dimension(66, 66));
        notificationButton.setSize(new java.awt.Dimension(66, 66));
        notificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(0, 204, 204));
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/default-profile.png"))); // NOI18N
        profileButton.setToolTipText("User Profile");
        profileButton.setMaximumSize(new java.awt.Dimension(66, 66));
        profileButton.setMinimumSize(new java.awt.Dimension(66, 66));
        profileButton.setPreferredSize(new java.awt.Dimension(66, 66));
        profileButton.setSize(new java.awt.Dimension(66, 66));
        profileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        statisticButton.setBackground(new java.awt.Color(255, 204, 0));
        statisticButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/stat-icon.png"))); // NOI18N
        statisticButton.setToolTipText("Statistics");
        statisticButton.setPreferredSize(new java.awt.Dimension(66, 66));
        statisticButton.setSize(new java.awt.Dimension(66, 66));
        statisticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticButtonActionPerformed(evt);
            }
        });

        foodRecButton.setBackground(new java.awt.Color(0, 204, 0));
        foodRecButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/food-icon.png"))); // NOI18N
        foodRecButton.setToolTipText("Food Recommendation");
        foodRecButton.setMaximumSize(new java.awt.Dimension(66, 66));
        foodRecButton.setMinimumSize(new java.awt.Dimension(66, 66));
        foodRecButton.setPreferredSize(new java.awt.Dimension(66, 66));
        foodRecButton.setSize(new java.awt.Dimension(66, 66));
        foodRecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodRecButtonActionPerformed(evt);
            }
        });

        intakeButton.setBackground(new java.awt.Color(153, 153, 255));
        intakeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mood-icon.png"))); // NOI18N
        intakeButton.setToolTipText("Mood & Intake");
        intakeButton.setMaximumSize(new java.awt.Dimension(66, 66));
        intakeButton.setMinimumSize(new java.awt.Dimension(66, 66));
        intakeButton.setPreferredSize(new java.awt.Dimension(66, 66));
        intakeButton.setSize(new java.awt.Dimension(66, 66));
        intakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodRecButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(notificationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statisticButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodRecButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Navigates user to the CrudIntakeController
     * @param evt 
     */
    private void intakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getCrudIntakeController();     
    }//GEN-LAST:event_intakeButtonActionPerformed

    /**
     * Navigates user to the CrudUserProfileController classes
     * @param evt 
     */
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getUserProfileController();
    }//GEN-LAST:event_profileButtonActionPerformed

    /**
     * Navigates user to the NotificationController
     * @param evt 
     */
    private void notificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getNotificationController();
    }//GEN-LAST:event_notificationButtonActionPerformed

    /**
     * Navigates user to the StatisticController
     * @param evt 
     */
    private void statisticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getStatisticController();
    }//GEN-LAST:event_statisticButtonActionPerformed

    /**
     * Navigates user to the FoodRecController
     * @param evt 
     */
    private void foodRecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodRecButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getFoodRecController();
    }//GEN-LAST:event_foodRecButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foodRecButton;
    private javax.swing.JButton intakeButton;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton notificationButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton statisticButton;
    // End of variables declaration//GEN-END:variables

}
