/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package NavigationController;

/**
 *
 * @author Gisward
 */
public class NavigationView extends javax.swing.JFrame 
{
    NavigationController parentNavigationController;
    
    /** 
     * Creates new form NavigationView 
     * @param parentNavigationController the original NavigationController object
     */
    public NavigationView(NavigationController parentNavigationController) 
    {
        this.parentNavigationController = parentNavigationController;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intakeButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        notificationButton = new javax.swing.JButton();
        statisticButton = new javax.swing.JButton();
        foodRecButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intakeButton.setBackground(new java.awt.Color(153, 153, 255));
        intakeButton.setText("Input Intake & Mood");
        intakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intakeButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(0, 204, 204));
        profileButton.setText("Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        notificationButton.setBackground(new java.awt.Color(0, 204, 153));
        notificationButton.setText("Notifications");
        notificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationButtonActionPerformed(evt);
            }
        });

        statisticButton.setBackground(new java.awt.Color(255, 204, 0));
        statisticButton.setText("Statistics");
        statisticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticButtonActionPerformed(evt);
            }
        });

        foodRecButton.setBackground(new java.awt.Color(0, 204, 0));
        foodRecButton.setText("Food Recommendations");
        foodRecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodRecButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notificationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statisticButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foodRecButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intakeButton)
                .addGap(18, 18, 18)
                .addComponent(profileButton)
                .addGap(18, 18, 18)
                .addComponent(notificationButton)
                .addGap(18, 18, 18)
                .addComponent(statisticButton)
                .addGap(18, 18, 18)
                .addComponent(foodRecButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Navigates user to the CrudIntakeController
     * @param evt 
     */
    private void intakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intakeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getCrudIntakeController();     
    }//GEN-LAST:event_intakeButtonActionPerformed

    /**
     * Navigates user to the CrudUserProfileController classes
     * @param evt 
     */
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getUserProfileController();
    }//GEN-LAST:event_profileButtonActionPerformed

    /**
     * Navigates user to the NotificationController
     * @param evt 
     */
    private void notificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getNotificationController();
    }//GEN-LAST:event_notificationButtonActionPerformed

    /**
     * Navigates user to the StatisticController
     * @param evt 
     */
    private void statisticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getStatisticController();
    }//GEN-LAST:event_statisticButtonActionPerformed

    /**
     * Navigates user to the FoodRecController
     * @param evt 
     */
    private void foodRecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodRecButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.parentNavigationController.getFoodRecController();
    }//GEN-LAST:event_foodRecButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton foodRecButton;
    private javax.swing.JButton intakeButton;
    private javax.swing.JButton notificationButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton statisticButton;
    // End of variables declaration//GEN-END:variables

}
