/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CrudIntakeView;

import CrudIntakeController.CrudIntakeController;
//import CrudIntakeModel.CrudIntakeModel;
import CrudIntakeModel.Food;
import CrudIntakeModel.Drink;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Gisward
 */
public class CrudIntakeView extends javax.swing.JFrame 
{
    CrudIntakeController theCrudIntakeController;
    Food f;
    Drink d;
    List<Food> fList = new ArrayList<Food>();
    List<Drink> dList = new ArrayList<Drink>();
  //  CrudIntakeModel cim;
    
    /** 
     * Creates new form CrudIntakeView 
     * @param parentCrudIntakeController the original CrudIntakeController object
     */
    public CrudIntakeView(CrudIntakeController parentCrudIntakeController) 
    {
        this.theCrudIntakeController = parentCrudIntakeController;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        intakeNameTF = new javax.swing.JTextField();
        intakeWeightTF = new javax.swing.JTextField();
        intakeTSCTF = new javax.swing.JTextField();
        intakeName = new javax.swing.JLabel();
        intakeWeight = new javax.swing.JLabel();
        intakeTSC = new javax.swing.JLabel();
        foodButton = new javax.swing.JButton();
        drinkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        intakeName.setText("Intake Name");

        intakeWeight.setText("Intake Weight");

        intakeTSC.setText("Time Since Consumption");

        foodButton.setText("Food");
        foodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButtonActionPerformed(evt);
            }
        });

        drinkButton.setText("Drink");
        drinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(homeButton)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intakeName)
                    .addComponent(intakeWeight)
                    .addComponent(intakeTSC)
                    .addComponent(foodButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(intakeTSCTF, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addComponent(intakeWeightTF)
                        .addComponent(intakeNameTF))
                    .addComponent(drinkButton))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intakeName))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeWeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intakeWeight))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intakeTSCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intakeTSC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodButton)
                    .addComponent(drinkButton))
                .addGap(15, 15, 15)
                .addComponent(homeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Navigates user to the original NavigationView
     * @param evt 
     */
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.theCrudIntakeController.requestNavigationView();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void foodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodButtonActionPerformed
        // TODO add your handling code here:
        String nameField = intakeNameTF.getText();
        Double weightField = Double.parseDouble(intakeWeightTF.getText());
        String tscField = String.valueOf(intakeTSCTF.getText());
        f = new Food(nameField, weightField, tscField);
        this.theCrudIntakeController.addFood(f);
        System.out.println(f.getName() + " " + f.getWeight() + " " + f.getTimeSinceLastConsumed() + " was added.");
        intakeNameTF.setText("");
        intakeWeightTF.setText("");
        intakeTSCTF.setText("");
    }//GEN-LAST:event_foodButtonActionPerformed

    private void drinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkButtonActionPerformed
        // TODO add your handling code here:
        String nameField = intakeNameTF.getText();
        Double weightField = Double.parseDouble(intakeWeightTF.getText());
        String tscField = String.valueOf(intakeTSCTF.getText());
        d = new Drink(nameField, weightField, tscField);
        this.theCrudIntakeController.addDrink(d);
        System.out.println(d.getName() + " " + d.getWeight() + " " + d.getTimeSinceLastConsumed() + " was added.");
        intakeNameTF.setText("");
        intakeWeightTF.setText("");
        intakeTSCTF.setText("");
    }//GEN-LAST:event_drinkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudIntakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudIntakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudIntakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudIntakeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                //new CrudIntakeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drinkButton;
    private javax.swing.JButton foodButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel intakeName;
    private javax.swing.JTextField intakeNameTF;
    private javax.swing.JLabel intakeTSC;
    private javax.swing.JTextField intakeTSCTF;
    private javax.swing.JLabel intakeWeight;
    private javax.swing.JTextField intakeWeightTF;
    // End of variables declaration//GEN-END:variables

}
