/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package StatisticView;

import StatisticController.StatisticController;
import NavigationController.NavigationController;

import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Gisward
 */
public class StatisticView extends javax.swing.JFrame 
{
    StatisticController theStatisticController;
    NavigationController theNavigationController;
    TableRowSorter<TableModel> rowSorterFood;
    TableRowSorter<TableModel> rowSorterDrink;
    TableRowSorter<TableModel> rowSorterMood;
    int rowFood;
    int rowDrink;
    int rowMood;
    
    /** 
     * Creates new form StatisticView 
     * @param  parentStatisticController the original StatisticController object
     */
    public StatisticView(StatisticController parentStatisticController, NavigationController parentNavigationController) 
    {
        this.theStatisticController = parentStatisticController;
        this.theNavigationController = parentNavigationController;
        initComponents();
        this.rowSorterFood = new TableRowSorter<>(this.foodTable.getModel());
        this.rowSorterDrink = new TableRowSorter<>(this.drinkTable.getModel());
        this.rowSorterMood = new TableRowSorter<>(this.moodTable.getModel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        foodRecFooter = new javax.swing.JButton();
        crudIntakeFooter = new javax.swing.JButton();
        foodScrollPane = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        drinkScrollPane = new javax.swing.JScrollPane();
        drinkTable = new javax.swing.JTable();
        drinkScrollPane1 = new javax.swing.JScrollPane();
        moodTable = new javax.swing.JTable();
        searchFoodButton = new javax.swing.JButton();
        searchDrinkButton = new javax.swing.JButton();
        searchDrinkTextField = new javax.swing.JTextField();
        searchMoodTextField = new javax.swing.JTextField();
        searchMoodButton = new javax.swing.JButton();
        searchFoodTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        backButton.setText("Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        foodRecFooter.setBackground(new java.awt.Color(0, 204, 0));
        foodRecFooter.setText("Food Recommendations");
        foodRecFooter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodRecFooterActionPerformed(evt);
            }
        });

        crudIntakeFooter.setBackground(new java.awt.Color(153, 153, 255));
        crudIntakeFooter.setText("Input Intake & Mood");
        crudIntakeFooter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudIntakeFooterActionPerformed(evt);
            }
        });

        foodScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        foodTable.setBackground(new java.awt.Color(204, 204, 255));
        foodTable.setModel(this.theStatisticController.getFoodTableModel());
        foodTable.setGridColor(new java.awt.Color(102, 102, 255));
        foodScrollPane.setViewportView(foodTable);

        drinkScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        drinkTable.setBackground(new java.awt.Color(255, 204, 204));
        drinkTable.setModel(this.theStatisticController.getDrinkTableModel());
        drinkTable.setGridColor(new java.awt.Color(255, 153, 153));
        drinkScrollPane.setViewportView(drinkTable);

        drinkScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        moodTable.setBackground(new java.awt.Color(255, 204, 204));
        moodTable.setModel(this.theStatisticController.getMoodTableModel());
        moodTable.setGridColor(new java.awt.Color(255, 153, 153));
        drinkScrollPane1.setViewportView(moodTable);

        searchFoodButton.setText("Search Foods");
        searchFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFoodButtonActionPerformed(evt);
            }
        });

        searchDrinkButton.setText("Search Drinks");
        searchDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDrinkButtonActionPerformed(evt);
            }
        });

        searchMoodButton.setText("Search Moods");
        searchMoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMoodButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(drinkScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foodScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(drinkScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchMoodTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchMoodButton)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchDrinkTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDrinkButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addComponent(crudIntakeFooter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foodRecFooter)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchFoodTextField)
                        .addGap(11, 11, 11)
                        .addComponent(searchFoodButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFoodButton)
                    .addComponent(searchFoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(drinkScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchDrinkButton)
                    .addComponent(searchDrinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(drinkScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchMoodButton)
                    .addComponent(searchMoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodRecFooter)
                    .addComponent(crudIntakeFooter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Navigates user to the original NavigationView
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.theStatisticController.requestNavigationView();
    }//GEN-LAST:event_backButtonActionPerformed

    private void foodRecFooterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodRecFooterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.theNavigationController.getFoodRecController();
    }//GEN-LAST:event_foodRecFooterActionPerformed

    private void crudIntakeFooterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudIntakeFooterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.theNavigationController.getCrudIntakeController();
    }//GEN-LAST:event_crudIntakeFooterActionPerformed

    private void searchFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFoodButtonActionPerformed
        // TODO add your handling code here:
        this.foodTable.setRowSorter(this.rowSorterFood);
        String searchedWord = this.searchFoodTextField.getText();
        
        if (searchedWord.trim().length() == 0)
        {
            rowSorterFood.setRowFilter(null);
        }
        else 
        {
            rowSorterFood.setRowFilter(RowFilter.regexFilter("(?i)" + searchedWord));
        }
    }//GEN-LAST:event_searchFoodButtonActionPerformed

    private void searchDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDrinkButtonActionPerformed
        // TODO add your handling code here:
        this.drinkTable.setRowSorter(this.rowSorterDrink);
        String searchedWord = this.searchDrinkTextField.getText();
        
        if (searchedWord.trim().length() == 0)
        {
            rowSorterDrink.setRowFilter(null);
        }
        else 
        {
            rowSorterDrink.setRowFilter(RowFilter.regexFilter("(?i)" + searchedWord));
        }
    }//GEN-LAST:event_searchDrinkButtonActionPerformed

    private void searchMoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMoodButtonActionPerformed
        // TODO add your handling code here:
        this.moodTable.setRowSorter(this.rowSorterMood);
        String searchedWord = this.searchMoodTextField.getText();
        
        if (searchedWord.trim().length() == 0)
        {
            rowSorterMood.setRowFilter(null);
        }
        else 
        {
            rowSorterMood.setRowFilter(RowFilter.regexFilter("(?i)" + searchedWord));
        }
    }//GEN-LAST:event_searchMoodButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                //new StatisticView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton crudIntakeFooter;
    private javax.swing.JScrollPane drinkScrollPane;
    private javax.swing.JScrollPane drinkScrollPane1;
    private javax.swing.JTable drinkTable;
    private javax.swing.JButton foodRecFooter;
    private javax.swing.JScrollPane foodScrollPane;
    private javax.swing.JTable foodTable;
    private javax.swing.JTable moodTable;
    private javax.swing.JButton searchDrinkButton;
    private javax.swing.JTextField searchDrinkTextField;
    private javax.swing.JButton searchFoodButton;
    private javax.swing.JTextField searchFoodTextField;
    private javax.swing.JButton searchMoodButton;
    private javax.swing.JTextField searchMoodTextField;
    // End of variables declaration//GEN-END:variables

}
